// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yanicfrwofkkhilubcud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhbmljZnJ3b2Zra2hpbHViY3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjAzNTYsImV4cCI6MjA3MDgzNjM1Nn0.qNMI3okazrOvwcrgbXdXZT_MZuGFRDgzqBktZ4jILyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
